// <auto-generated />
using System;
using BlazedCosmos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazedCosmos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazedCosmos.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BlazedCosmos.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BlazedCosmos.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A stunning galaxy art print",
                            ImageUrl = "/images/1.jpg",
                            Name = "Galaxy Print",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A vibrant nebula art print",
                            ImageUrl = "/images/2.jpg",
                            Name = "Cosmic Nebula",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A mesmerizing starry night print",
                            ImageUrl = "/images/3.jpg",
                            Name = "Starry Night",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A dramatic solar flare art print",
                            ImageUrl = "/images/4.jpg",
                            Name = "Solar Flare",
                            Price = 2100m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A beautiful aurora borealis print",
                            ImageUrl = "/images/5.jpg",
                            Name = "Aurora Borealis",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "A breathtaking Milky Way art print",
                            ImageUrl = "/images/6.jpg",
                            Name = "Milky Way",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 7,
                            Description = "A unique planetary orbit print",
                            ImageUrl = "/images/7.jpg",
                            Name = "Planetary Orbit",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 8,
                            Description = "A mysterious black hole art print",
                            ImageUrl = "/images/8.jpg",
                            Name = "Black Hole",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("BlazedCosmos.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazedCosmos.Models.CartItem", b =>
                {
                    b.HasOne("BlazedCosmos.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BlazedCosmos.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
